version: '3.7'

services:

  newsfeed:
    build: ./
    environment:
      LOG_LEVEL: "DEBUG"
      API_BASE_PATH: "/api/"
      EVENT_STORAGE_DSN: "redis://redis:6379?db=0&connection_timeout=5&minsize=5&maxsize=10"
    volumes:
      - './:/code'

  redis:
    image: "redis:alpine"

  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./swagger:/usr/share/nginx/html/swagger/
      - ./demo_app/build/:/usr/share/nginx/html/demo_app/
